# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Addons concerning Odoo's social ERP features and messaging in general.
repo_name: social
repo_slug: social
repo_website: https://github.com/OCA/social
travis_apt_packages: []
travis_apt_sources: []
