[project]
name = "odoo-addons-oca-social"
version = "18.0.20241028.0"
dependencies = [
    "odoo-addon-mail_thread_create_nolog==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
